### ISSUE TITLE
checks

### ISSUE THREAD

**Issue by melsod** [melsod/OCSWinter2020#28]
Hahaha, I found the attention check too hard. It took me a while to figure out that you needed the LAST letter of one of the colours. If this is a standard check, fine, I'm just not a very good attender. But if it's not standard, maybe pick something easier. ;-)

**Comment by SmithBradleyC** [comment]
Honestly, I have no idea what is standard, or if there is anything that is standard...After asking someone who has done experiments with attention checks, I was told that there isn't really a standard between different procedures. I personally like it so that it shows people are actually paying attention but I've made the words "first" and "last" bold so it's more obvious. If others have opinions then speak up.

**Comment by saramontazeri** [comment]
I found the attention check easy and fast. I think the instruction was understandable but if you mention that they should **use the keyboard** and press the first or last letter of the word they hear, it would be easier. Also, I suggest you change the words "first" and "last" to capital letters too.
